name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore -p:Version=${GITHUB_REF##*/v}
        
      - name: Test
        run: dotnet test -c Release --no-build

      - name: Package
        run: dotnet pack -c Release --no-build -o nupkgs -p:PackageVersion=${GITHUB_REF##*/v} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nupkgs/*.nupkg
            nupkgs/*.snupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: dotnet nuget push nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}

      - name: Publish snupkg
        run: dotnet nuget push nupkgs/*.snupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
